manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ethan605
      url-base: https://github.com/ethan605
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: edf5c0814fd3ea202e43aad2d68fd32e882a518c   # v0.3.0
      import: app/west.yml       # Pulls in Zephyr and all ZMK dependencies
    - name: zmk-dongle-screen
      remote: ethan605
      revision: 26833cbca25b4cc76de4559149dc96a78bfd3b6b   # feat(corne-custom)
  self:
    path: config
